[tool.poetry]
name = "repo-chunker"
version = "0.1.0"
description = "Repository chunker package"
authors = [
    {name = "KonstFed", email = "konstantin_fedorov_03@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
packages = [{include = "repo_chunker", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

