[tool.poetry]
name = "ragcore-monorepo"
version = "0.1.0"
description = "RAG Core monorepo"
authors = ["KonstFed <konstfed12@gmail.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry-workspace]
members = [
    "packages/repo_chunker",
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

