version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - [%(levelname)s] - %(name)s - (%(filename)s:%(lineno)d) - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json: # Задел на будущее для ELK/Grafana
    format: "%(asctime)s %(levelname)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

loggers:
  # Наш корневой логгер приложения
  RAGService:
    level: DEBUG
    handlers: [console]
    propagate: false
  
  # Сторонние библиотеки (чтобы не мусорили)
  urllib3:
    level: WARNING
  asyncio:
    level: WARNING

root:
  level: INFO
  handlers: [console]
