chunkers:
  python:
    language: python
    max_chunk_size: 1000
    chunk_overlap: 10
    chunk_expansion: true
    metadata_template: default
    extensions:
    - .py
  java:
    language: java
    max_chunk_size: 1200
    chunk_overlap: 15
    chunk_expansion: true
    metadata_template: default
    extensions:
    - .java
  typescript:
    language: typescript
    max_chunk_size: 1100
    chunk_overlap: 10
    chunk_expansion: true
    metadata_template: default
    extensions:
    - .ts
    - .tsx
  csharp:
    language: csharp
    max_chunk_size: 1000
    chunk_overlap: 10
    chunk_expansion: true
    metadata_template: default
    extensions:
    - .cs
